### ISSUE TITLE
add support for symfony 3.4 and symfony 4.0

### ISSUE THREAD

**Issue by bogdandovgopol** [schmittjoh/JMSI18nRoutingBundle#215]
Hi,

please add support for Symfony 3.4 and Symfony 4.0

Current error:

> The "jms_i18n_routing.loader" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

**Comment by bravik** [comment]
"jms_i18n_routing.loader" should be declared as public
Solved by editing the following line in `JMSI18nRoutingBundle/Resources/config/services.xml`:
`<service id="jms_i18n_routing.loader" class="%jms_i18n_routing.loader.class%" public="true">`

**Comment by acasademont** [comment]
hi guys! i'll try to work it out and review all these SF4 compatibility this weekend :) Thx for the patches!

**Comment by acasademont** [comment]
Done :)

**Comment by kironet** [comment]
@acasademont Hi, I don't know why, but I'm still having the same error. My composer: 
`"jms/i18n-routing-bundle": "^2.0",`

**Comment by web-monster** [comment]
Please, Add support version 3.4

**Comment by acasademont** [comment]
As it has a BC break you need to use ^3.0!

**Comment by pdias** [comment]
This bundle in Sf3.4 will continue without correcting this warning, because most bundles in Sf3. * continue to use symfony/framework-bundle 3. * and now is required "symfony/framework-bundle": "^4.0" .

I do not know if it will be possible ... but why not create a tag 2.0.2 where only correct the services.xml (public="true") as already mentioned?!!!

**Comment by acasademont** [comment]
@pdias done, I've tagged 2.0.2 with the service fix

**Comment by pdias** [comment]
Thanks @acasademont

**Comment by edurenye** [comment]
I'm still having the following error:

> User Deprecated: The "router" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0

With the version 2.0.2 and Symfony 3.4.1

**Comment by acasademont** [comment]
@edurenye seems like this is a different issue, could you please open up a new one?

**Comment by edurenye** [comment]
Done.
